import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [
		esbuildSvelte({
		  compilerOptions: { css: 'injected'},
		  // verbatimModuleSyntax is required by svelte-preprocess v6: without it
		  // the TS transpile strips component imports that are only used in
		  // markup, leaving undefined references in the bundle.
		  preprocess: sveltePreprocess({
		    typescript: { compilerOptions: { verbatimModuleSyntax: true } },
		  }),
		}),
	],
	define: {
		'process.env.FORESTRY_BASE_URL': JSON.stringify(process.env.FORESTRY_BASE_URL || "https://api.forestry.md/app"),
	},
}).catch(() => process.exit(1));
